/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE134_Uncontrolled_Format_String__char_file_vprintf_01_good();");
	CWE134_Uncontrolled_Format_String__char_file_vprintf_01_good();

	printLine("Calling CWE134_Uncontrolled_Format_String__char_file_vprintf_22_good();");
	CWE134_Uncontrolled_Format_String__char_file_vprintf_22_good();


	printLine("Calling CWE134_Uncontrolled_Format_String__char_file_w32_vsnprintf_01_good();");
	CWE134_Uncontrolled_Format_String__char_file_w32_vsnprintf_01_good();

	printLine("Calling CWE134_Uncontrolled_Format_String__char_file_w32_vsnprintf_22_good();");
	CWE134_Uncontrolled_Format_String__char_file_w32_vsnprintf_22_good();


	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_fprintf_01_good();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_fprintf_01_good();

	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_fprintf_22_good();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_fprintf_22_good();


	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_printf_01_good();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_printf_01_good();


	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_printf_22_good();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_printf_22_good();

	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_snprintf_01_good();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_snprintf_01_good();


	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_snprintf_22_good();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_snprintf_22_good();

	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_vfprintf_01_good();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_vfprintf_01_good();

	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_vfprintf_22_good();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_vfprintf_22_good();

	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_vprintf_01_good();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_vprintf_01_good();

	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_vprintf_22_good();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_vprintf_22_good();


	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_w32_vsnprintf_01_good();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_w32_vsnprintf_01_good();

	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_w32_vsnprintf_22_good();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_w32_vsnprintf_22_good();


	printLine("Calling CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_fprintf_01_good();");
	CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_fprintf_01_good();

	printLine("Calling CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_fprintf_22_good();");
	CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_fprintf_22_good();


	printLine("Calling CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_printf_01_good();");
	CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_printf_01_good();


	printLine("Calling CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_printf_22_good();");
	CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_printf_22_good();


	printLine("Calling CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_snprintf_01_good();");
	CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_snprintf_01_good();


	printLine("Calling CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_snprintf_22_good();");
	CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_snprintf_22_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */


#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	
	printLine("Calling CWE134_Uncontrolled_Format_String__char_file_vprintf_01_bad();");
	CWE134_Uncontrolled_Format_String__char_file_vprintf_01_bad();

	printLine("Calling CWE134_Uncontrolled_Format_String__char_file_vprintf_22_bad();");
	CWE134_Uncontrolled_Format_String__char_file_vprintf_22_bad();


	printLine("Calling CWE134_Uncontrolled_Format_String__char_file_w32_vsnprintf_01_bad();");
	CWE134_Uncontrolled_Format_String__char_file_w32_vsnprintf_01_bad();

	printLine("Calling CWE134_Uncontrolled_Format_String__char_file_w32_vsnprintf_22_bad();");
	CWE134_Uncontrolled_Format_String__char_file_w32_vsnprintf_22_bad();


	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_fprintf_01_bad();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_fprintf_01_bad();

	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_fprintf_22_bad();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_fprintf_22_bad();


	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_printf_01_bad();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_printf_01_bad();


	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_printf_22_bad();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_printf_22_bad();

	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_snprintf_01_bad();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_snprintf_01_bad();


	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_snprintf_22_bad();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_snprintf_22_bad();

	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_vfprintf_01_bad();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_vfprintf_01_bad();

	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_vfprintf_22_bad();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_vfprintf_22_bad();

	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_vprintf_01_bad();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_vprintf_01_bad();

	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_vprintf_22_bad();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_vprintf_22_bad();


	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_w32_vsnprintf_01_bad();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_w32_vsnprintf_01_bad();

	printLine("Calling CWE134_Uncontrolled_Format_String__char_listen_socket_w32_vsnprintf_22_bad();");
	CWE134_Uncontrolled_Format_String__char_listen_socket_w32_vsnprintf_22_bad();


	printLine("Calling CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_fprintf_01_bad();");
	CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_fprintf_01_bad();

	printLine("Calling CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_fprintf_22_bad();");
	CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_fprintf_22_bad();


	printLine("Calling CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_printf_01_bad();");
	CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_printf_01_bad();


	printLine("Calling CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_printf_22_bad();");
	CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_printf_22_bad();


	printLine("Calling CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_snprintf_01_bad();");
	CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_snprintf_01_bad();


	printLine("Calling CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_snprintf_22_bad();");
	CWE134_Uncontrolled_Format_String__wchar_t_connect_socket_snprintf_22_bad();
#endif /* OMITBAD */

	return 0;

} 
