/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE681_Incorrect_Conversion_Between_Numeric_Types__double2float_01_good();");
	CWE681_Incorrect_Conversion_Between_Numeric_Types__double2float_01_good();


	printLine("Calling CWE681_Incorrect_Conversion_Between_Numeric_Types__double2float_13_good();");
	CWE681_Incorrect_Conversion_Between_Numeric_Types__double2float_13_good();


	printLine("Calling CWE681_Incorrect_Conversion_Between_Numeric_Types__double2int_01_good();");
	CWE681_Incorrect_Conversion_Between_Numeric_Types__double2int_01_good();


	printLine("Calling CWE681_Incorrect_Conversion_Between_Numeric_Types__double2int_13_good();");
	CWE681_Incorrect_Conversion_Between_Numeric_Types__double2int_13_good();


	printLine("Calling CWE681_Incorrect_Conversion_Between_Numeric_Types__doubleNaN2int_01_good();");
	CWE681_Incorrect_Conversion_Between_Numeric_Types__doubleNaN2int_01_good();


	printLine("Calling CWE681_Incorrect_Conversion_Between_Numeric_Types__doubleNaN2int_13_good();");
	CWE681_Incorrect_Conversion_Between_Numeric_Types__doubleNaN2int_13_good();


#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	printLine("Calling CWE681_Incorrect_Conversion_Between_Numeric_Types__double2float_01_bad();");
	CWE681_Incorrect_Conversion_Between_Numeric_Types__double2float_01_bad();


	printLine("Calling CWE681_Incorrect_Conversion_Between_Numeric_Types__double2float_13_bad();");
	CWE681_Incorrect_Conversion_Between_Numeric_Types__double2float_13_bad();


	printLine("Calling CWE681_Incorrect_Conversion_Between_Numeric_Types__double2int_01_bad();");
	CWE681_Incorrect_Conversion_Between_Numeric_Types__double2int_01_bad();

	printLine("Calling CWE681_Incorrect_Conversion_Between_Numeric_Types__double2int_13_bad();");
	CWE681_Incorrect_Conversion_Between_Numeric_Types__double2int_13_bad();


	printLine("Calling CWE681_Incorrect_Conversion_Between_Numeric_Types__doubleNaN2int_01_bad();");
	CWE681_Incorrect_Conversion_Between_Numeric_Types__doubleNaN2int_01_bad();


	printLine("Calling CWE681_Incorrect_Conversion_Between_Numeric_Types__doubleNaN2int_13_bad();");
	CWE681_Incorrect_Conversion_Between_Numeric_Types__doubleNaN2int_13_bad();


#endif /* OMITBAD */

	return 0;

} 
