/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE775_Missing_Release_of_File_Descriptor_or_Handle__fopen_no_close_01_good();");
	CWE775_Missing_Release_of_File_Descriptor_or_Handle__fopen_no_close_01_good();


	printLine("Calling CWE775_Missing_Release_of_File_Descriptor_or_Handle__fopen_no_close_18_good();");
	CWE775_Missing_Release_of_File_Descriptor_or_Handle__fopen_no_close_18_good();


	printLine("Calling CWE775_Missing_Release_of_File_Descriptor_or_Handle__open_no_close_01_good();");
	CWE775_Missing_Release_of_File_Descriptor_or_Handle__open_no_close_01_good();


	printLine("Calling CWE775_Missing_Release_of_File_Descriptor_or_Handle__open_no_close_18_good();");
	CWE775_Missing_Release_of_File_Descriptor_or_Handle__open_no_close_18_good();


	printLine("Calling CWE775_Missing_Release_of_File_Descriptor_or_Handle__w32CreateFile_no_close_01_good();");
	CWE775_Missing_Release_of_File_Descriptor_or_Handle__w32CreateFile_no_close_01_good();


	printLine("Calling CWE775_Missing_Release_of_File_Descriptor_or_Handle__w32CreateFile_no_close_18_good();");
	CWE775_Missing_Release_of_File_Descriptor_or_Handle__w32CreateFile_no_close_18_good();


#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	
	printLine("Calling CWE775_Missing_Release_of_File_Descriptor_or_Handle__fopen_no_close_01_bad();");
	CWE775_Missing_Release_of_File_Descriptor_or_Handle__fopen_no_close_01_bad();


	printLine("Calling CWE775_Missing_Release_of_File_Descriptor_or_Handle__fopen_no_close_18_bad();");
	CWE775_Missing_Release_of_File_Descriptor_or_Handle__fopen_no_close_18_bad();


	printLine("Calling CWE775_Missing_Release_of_File_Descriptor_or_Handle__open_no_close_01_bad();");
	CWE775_Missing_Release_of_File_Descriptor_or_Handle__open_no_close_01_bad();


	printLine("Calling CWE775_Missing_Release_of_File_Descriptor_or_Handle__open_no_close_18_bad();");
	CWE775_Missing_Release_of_File_Descriptor_or_Handle__open_no_close_18_bad();


	printLine("Calling CWE775_Missing_Release_of_File_Descriptor_or_Handle__w32CreateFile_no_close_01_bad();");
	CWE775_Missing_Release_of_File_Descriptor_or_Handle__w32CreateFile_no_close_01_bad();


	printLine("Calling CWE775_Missing_Release_of_File_Descriptor_or_Handle__w32CreateFile_no_close_18_bad();");
	CWE775_Missing_Release_of_File_Descriptor_or_Handle__w32CreateFile_no_close_18_bad();
#endif /* OMITBAD */

	return 0;

} 
