/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE190_Integer_Overflow__int64_t_fscanf_square_01_good();");
	CWE190_Integer_Overflow__int64_t_fscanf_square_01_good();

	printLine("Calling CWE190_Integer_Overflow__int64_t_fscanf_square_52_good();");
	CWE190_Integer_Overflow__int64_t_fscanf_square_52_good();

	printLine("Calling CWE190_Integer_Overflow__int64_t_max_add_01_good();");
	CWE190_Integer_Overflow__int64_t_max_add_01_good();


	printLine("Calling CWE190_Integer_Overflow__int64_t_max_add_52_good();");
	CWE190_Integer_Overflow__int64_t_max_add_52_good();

	printLine("Calling CWE190_Integer_Overflow__int64_t_max_multiply_01_good();");
	CWE190_Integer_Overflow__int64_t_max_multiply_01_good();

	printLine("Calling CWE190_Integer_Overflow__int64_t_max_multiply_52_good();");
	CWE190_Integer_Overflow__int64_t_max_multiply_52_good();


	printLine("Calling CWE190_Integer_Overflow__int64_t_max_square_01_good();");
	CWE190_Integer_Overflow__int64_t_max_square_01_good();

	printLine("Calling CWE190_Integer_Overflow__int64_t_max_square_52_good();");
	CWE190_Integer_Overflow__int64_t_max_square_52_good();

	printLine("Calling CWE190_Integer_Overflow__int64_t_rand_add_01_good();");
	CWE190_Integer_Overflow__int64_t_rand_add_01_good();


	printLine("Calling CWE190_Integer_Overflow__int64_t_rand_add_52_good();");
	CWE190_Integer_Overflow__int64_t_rand_add_52_good();


	printLine("Calling CWE190_Integer_Overflow__int64_t_rand_multiply_01_good();");
	CWE190_Integer_Overflow__int64_t_rand_multiply_01_good();


	printLine("Calling CWE190_Integer_Overflow__int64_t_rand_multiply_52_good();");
	CWE190_Integer_Overflow__int64_t_rand_multiply_52_good();


	printLine("Calling CWE190_Integer_Overflow__int64_t_rand_square_01_good();");
	CWE190_Integer_Overflow__int64_t_rand_square_01_good();


	printLine("Calling CWE190_Integer_Overflow__int64_t_rand_square_52_good();");
	CWE190_Integer_Overflow__int64_t_rand_square_52_good();

	printLine("Calling CWE190_Integer_Overflow__int_connect_socket_add_01_good();");
	CWE190_Integer_Overflow__int_connect_socket_add_01_good();


	printLine("Calling CWE190_Integer_Overflow__int_connect_socket_add_52_good();");
	CWE190_Integer_Overflow__int_connect_socket_add_52_good();


	printLine("Calling CWE190_Integer_Overflow__int_connect_socket_multiply_01_good();");
	CWE190_Integer_Overflow__int_connect_socket_multiply_01_good();


	printLine("Calling CWE190_Integer_Overflow__int_connect_socket_multiply_52_good();");
	CWE190_Integer_Overflow__int_connect_socket_multiply_52_good();


	printLine("Calling CWE190_Integer_Overflow__int_connect_socket_square_01_good();");
	CWE190_Integer_Overflow__int_connect_socket_square_01_good();


	printLine("Calling CWE190_Integer_Overflow__int_connect_socket_square_52_good();");
	CWE190_Integer_Overflow__int_connect_socket_square_52_good();


	printLine("Calling CWE190_Integer_Overflow__int_fgets_add_01_good();");
	CWE190_Integer_Overflow__int_fgets_add_01_good();


	printLine("Calling CWE190_Integer_Overflow__int_fgets_add_52_good();");
	CWE190_Integer_Overflow__int_fgets_add_52_good();


	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */



#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	
	printLine("Calling CWE190_Integer_Overflow__int64_t_fscanf_square_01_bad();");
	CWE190_Integer_Overflow__int64_t_fscanf_square_01_bad();

	printLine("Calling CWE190_Integer_Overflow__int64_t_fscanf_square_52_bad();");
	CWE190_Integer_Overflow__int64_t_fscanf_square_52_bad();

	printLine("Calling CWE190_Integer_Overflow__int64_t_max_add_01_bad();");
	CWE190_Integer_Overflow__int64_t_max_add_01_bad();


	printLine("Calling CWE190_Integer_Overflow__int64_t_max_add_52_bad();");
	CWE190_Integer_Overflow__int64_t_max_add_52_bad();

	printLine("Calling CWE190_Integer_Overflow__int64_t_max_multiply_01_bad();");
	CWE190_Integer_Overflow__int64_t_max_multiply_01_bad();

	printLine("Calling CWE190_Integer_Overflow__int64_t_max_multiply_52_bad();");
	CWE190_Integer_Overflow__int64_t_max_multiply_52_bad();


	printLine("Calling CWE190_Integer_Overflow__int64_t_max_square_01_bad();");
	CWE190_Integer_Overflow__int64_t_max_square_01_bad();

	printLine("Calling CWE190_Integer_Overflow__int64_t_max_square_52_bad();");
	CWE190_Integer_Overflow__int64_t_max_square_52_bad();

	printLine("Calling CWE190_Integer_Overflow__int64_t_rand_add_01_bad();");
	CWE190_Integer_Overflow__int64_t_rand_add_01_bad();


	printLine("Calling CWE190_Integer_Overflow__int64_t_rand_add_52_bad();");
	CWE190_Integer_Overflow__int64_t_rand_add_52_bad();


	printLine("Calling CWE190_Integer_Overflow__int64_t_rand_multiply_01_bad();");
	CWE190_Integer_Overflow__int64_t_rand_multiply_01_bad();


	printLine("Calling CWE190_Integer_Overflow__int64_t_rand_multiply_52_bad();");
	CWE190_Integer_Overflow__int64_t_rand_multiply_52_bad();


	printLine("Calling CWE190_Integer_Overflow__int64_t_rand_square_01_bad();");
	CWE190_Integer_Overflow__int64_t_rand_square_01_bad();


	printLine("Calling CWE190_Integer_Overflow__int64_t_rand_square_52_bad();");
	CWE190_Integer_Overflow__int64_t_rand_square_52_bad();

	printLine("Calling CWE190_Integer_Overflow__int_connect_socket_add_01_bad();");
	CWE190_Integer_Overflow__int_connect_socket_add_01_bad();


	printLine("Calling CWE190_Integer_Overflow__int_connect_socket_add_52_bad();");
	CWE190_Integer_Overflow__int_connect_socket_add_52_bad();


	printLine("Calling CWE190_Integer_Overflow__int_connect_socket_multiply_01_bad();");
	CWE190_Integer_Overflow__int_connect_socket_multiply_01_bad();


	printLine("Calling CWE190_Integer_Overflow__int_connect_socket_multiply_52_bad();");
	CWE190_Integer_Overflow__int_connect_socket_multiply_52_bad();


	printLine("Calling CWE190_Integer_Overflow__int_connect_socket_square_01_bad();");
	CWE190_Integer_Overflow__int_connect_socket_square_01_bad();


	printLine("Calling CWE190_Integer_Overflow__int_connect_socket_square_52_bad();");
	CWE190_Integer_Overflow__int_connect_socket_square_52_bad();


	printLine("Calling CWE190_Integer_Overflow__int_fgets_add_01_bad();");
	CWE190_Integer_Overflow__int_fgets_add_01_bad();


	printLine("Calling CWE190_Integer_Overflow__int_fgets_add_52_bad();");
	CWE190_Integer_Overflow__int_fgets_add_52_bad();
#endif /* OMITBAD */

	return 0;

} 
