/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE369_Divide_by_Zero__int_fscanf_modulo_01_good();");
	CWE369_Divide_by_Zero__int_fscanf_modulo_01_good();


	printLine("Calling CWE369_Divide_by_Zero__int_fscanf_modulo_12_good();");
	CWE369_Divide_by_Zero__int_fscanf_modulo_12_good();


	printLine("Calling CWE369_Divide_by_Zero__int_listen_socket_divide_01_good();");
	CWE369_Divide_by_Zero__int_listen_socket_divide_01_good();

	printLine("Calling CWE369_Divide_by_Zero__int_listen_socket_divide_13_good();");
	CWE369_Divide_by_Zero__int_listen_socket_divide_13_good();


	printLine("Calling CWE369_Divide_by_Zero__int_listen_socket_modulo_01_good();");
	CWE369_Divide_by_Zero__int_listen_socket_modulo_01_good();


	printLine("Calling CWE369_Divide_by_Zero__int_listen_socket_modulo_14_good();");
	CWE369_Divide_by_Zero__int_listen_socket_modulo_14_good();


	printLine("Calling CWE369_Divide_by_Zero__int_rand_divide_01_good();");
	CWE369_Divide_by_Zero__int_rand_divide_01_good();

	printLine("Calling CWE369_Divide_by_Zero__int_rand_divide_15_good();");
	CWE369_Divide_by_Zero__int_rand_divide_15_good();


	printLine("Calling CWE369_Divide_by_Zero__int_rand_modulo_01_good();");
	CWE369_Divide_by_Zero__int_rand_modulo_01_good();


	printLine("Calling CWE369_Divide_by_Zero__int_rand_modulo_16_good();");
	CWE369_Divide_by_Zero__int_rand_modulo_16_good();


	printLine("Calling CWE369_Divide_by_Zero__int_zero_divide_01_good();");
	CWE369_Divide_by_Zero__int_zero_divide_01_good();


	printLine("Calling CWE369_Divide_by_Zero__int_zero_divide_17_good();");
	CWE369_Divide_by_Zero__int_zero_divide_17_good();


	printLine("Calling CWE369_Divide_by_Zero__int_zero_modulo_01_good();");
	CWE369_Divide_by_Zero__int_zero_modulo_01_good();


	printLine("Calling CWE369_Divide_by_Zero__int_zero_modulo_18_good();");
	CWE369_Divide_by_Zero__int_zero_modulo_18_good();


	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */


#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	
	printLine("Calling CWE369_Divide_by_Zero__int_fscanf_modulo_01_bad();");
	CWE369_Divide_by_Zero__int_fscanf_modulo_01_bad();


	printLine("Calling CWE369_Divide_by_Zero__int_fscanf_modulo_12_bad();");
	CWE369_Divide_by_Zero__int_fscanf_modulo_12_bad();


	printLine("Calling CWE369_Divide_by_Zero__int_listen_socket_divide_01_bad();");
	CWE369_Divide_by_Zero__int_listen_socket_divide_01_bad();

	printLine("Calling CWE369_Divide_by_Zero__int_listen_socket_divide_13_bad();");
	CWE369_Divide_by_Zero__int_listen_socket_divide_13_bad();


	printLine("Calling CWE369_Divide_by_Zero__int_listen_socket_modulo_01_bad();");
	CWE369_Divide_by_Zero__int_listen_socket_modulo_01_bad();


	printLine("Calling CWE369_Divide_by_Zero__int_listen_socket_modulo_14_bad();");
	CWE369_Divide_by_Zero__int_listen_socket_modulo_14_bad();


	printLine("Calling CWE369_Divide_by_Zero__int_rand_divide_01_bad();");
	CWE369_Divide_by_Zero__int_rand_divide_01_bad();

	printLine("Calling CWE369_Divide_by_Zero__int_rand_divide_15_bad();");
	CWE369_Divide_by_Zero__int_rand_divide_15_bad();


	printLine("Calling CWE369_Divide_by_Zero__int_rand_modulo_01_bad();");
	CWE369_Divide_by_Zero__int_rand_modulo_01_bad();


	printLine("Calling CWE369_Divide_by_Zero__int_rand_modulo_16_bad();");
	CWE369_Divide_by_Zero__int_rand_modulo_16_bad();


	printLine("Calling CWE369_Divide_by_Zero__int_zero_divide_01_bad();");
	CWE369_Divide_by_Zero__int_zero_divide_01_bad();


	printLine("Calling CWE369_Divide_by_Zero__int_zero_divide_17_bad();");
	CWE369_Divide_by_Zero__int_zero_divide_17_bad();


	printLine("Calling CWE369_Divide_by_Zero__int_zero_modulo_01_bad();");
	CWE369_Divide_by_Zero__int_zero_modulo_01_bad();


	printLine("Calling CWE369_Divide_by_Zero__int_zero_modulo_18_bad();");
	CWE369_Divide_by_Zero__int_zero_modulo_18_bad();
#endif /* OMITBAD */

	return 0;

} 
