/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_char_connect_socket_01_good();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_char_connect_socket_01_good();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_char_connect_socket_12_good();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_char_connect_socket_12_good();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_char_fgets_01_good();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_char_fgets_01_good();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_char_fgets_12_good();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_char_fgets_12_good();

	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_char_fscanf_01_good();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_char_fscanf_01_good();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_char_fscanf_12_good();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_char_fscanf_12_good();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_char_listen_socket_01_good();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_char_listen_socket_01_good();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_char_listen_socket_12_good();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_char_listen_socket_12_good();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_char_rand_01_good();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_char_rand_01_good();

	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_char_rand_12_good();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_char_rand_12_good();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_connect_socket_01_good();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_connect_socket_01_good();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_connect_socket_12_good();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_connect_socket_12_good();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_fgets_01_good();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_fgets_01_good();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_fgets_12_good();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_fgets_12_good();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_fscanf_01_good();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_fscanf_01_good();

	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_fscanf_12_good();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_fscanf_12_good();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_listen_socket_01_good();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_listen_socket_01_good();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_listen_socket_12_good();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_listen_socket_12_good();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_rand_01_good();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_rand_01_good();

	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_rand_12_good();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_rand_12_good();


#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	
	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_char_connect_socket_01_bad();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_char_connect_socket_01_bad();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_char_connect_socket_12_bad();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_char_connect_socket_12_bad();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_char_fgets_01_bad();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_char_fgets_01_bad();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_char_fgets_12_bad();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_char_fgets_12_bad();

	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_char_fscanf_01_bad();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_char_fscanf_01_bad();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_char_fscanf_12_bad();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_char_fscanf_12_bad();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_char_listen_socket_01_bad();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_char_listen_socket_01_bad();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_char_listen_socket_12_bad();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_char_listen_socket_12_bad();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_char_rand_01_bad();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_char_rand_01_bad();

	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_char_rand_12_bad();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_char_rand_12_bad();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_connect_socket_01_bad();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_connect_socket_01_bad();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_connect_socket_12_bad();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_connect_socket_12_bad();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_fgets_01_bad();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_fgets_01_bad();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_fgets_12_bad();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_fgets_12_bad();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_fscanf_01_bad();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_fscanf_01_bad();

	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_fscanf_12_bad();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_fscanf_12_bad();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_listen_socket_01_bad();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_listen_socket_01_bad();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_listen_socket_12_bad();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_listen_socket_12_bad();


	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_rand_01_bad();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_rand_01_bad();

	printLine("Calling CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_rand_12_bad();");
	CWE789_Uncontrolled_Mem_Alloc__malloc_wchar_t_rand_12_bad();
#endif /* OMITBAD */

	return 0;

} 
