/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE194_Unexpected_Sign_Extension__listen_socket_malloc_01_good();");
	CWE194_Unexpected_Sign_Extension__listen_socket_malloc_01_good();


	printLine("Calling CWE194_Unexpected_Sign_Extension__listen_socket_malloc_52_good();");
	CWE194_Unexpected_Sign_Extension__listen_socket_malloc_52_good();

	printLine("Calling CWE194_Unexpected_Sign_Extension__listen_socket_memcpy_01_good();");
	CWE194_Unexpected_Sign_Extension__listen_socket_memcpy_01_good();


	printLine("Calling CWE194_Unexpected_Sign_Extension__listen_socket_memcpy_52_good();");
	CWE194_Unexpected_Sign_Extension__listen_socket_memcpy_52_good();

	printLine("Calling CWE194_Unexpected_Sign_Extension__listen_socket_memmove_01_good();");
	CWE194_Unexpected_Sign_Extension__listen_socket_memmove_01_good();


	printLine("Calling CWE194_Unexpected_Sign_Extension__listen_socket_memmove_52_good();");
	CWE194_Unexpected_Sign_Extension__listen_socket_memmove_52_good();


	printLine("Calling CWE194_Unexpected_Sign_Extension__listen_socket_strncpy_01_good();");
	CWE194_Unexpected_Sign_Extension__listen_socket_strncpy_01_good();

	printLine("Calling CWE194_Unexpected_Sign_Extension__listen_socket_strncpy_52_good();");
	CWE194_Unexpected_Sign_Extension__listen_socket_strncpy_52_good();

	printLine("Calling CWE194_Unexpected_Sign_Extension__negative_malloc_01_good();");
	CWE194_Unexpected_Sign_Extension__negative_malloc_01_good();


	printLine("Calling CWE194_Unexpected_Sign_Extension__negative_malloc_52_good();");
	CWE194_Unexpected_Sign_Extension__negative_malloc_52_good();

	printLine("Calling CWE194_Unexpected_Sign_Extension__negative_memcpy_01_good();");
	CWE194_Unexpected_Sign_Extension__negative_memcpy_01_good();


	printLine("Calling CWE194_Unexpected_Sign_Extension__negative_memcpy_52_good();");
	CWE194_Unexpected_Sign_Extension__negative_memcpy_52_good();


	printLine("Calling CWE194_Unexpected_Sign_Extension__negative_memmove_01_good();");
	CWE194_Unexpected_Sign_Extension__negative_memmove_01_good();


	printLine("Calling CWE194_Unexpected_Sign_Extension__negative_memmove_52_good();");
	CWE194_Unexpected_Sign_Extension__negative_memmove_52_good();

	printLine("Calling CWE194_Unexpected_Sign_Extension__negative_strncpy_01_good();");
	CWE194_Unexpected_Sign_Extension__negative_strncpy_01_good();


	printLine("Calling CWE194_Unexpected_Sign_Extension__negative_strncpy_52_good();");
	CWE194_Unexpected_Sign_Extension__negative_strncpy_52_good();


	printLine("Calling CWE194_Unexpected_Sign_Extension__rand_malloc_01_good();");
	CWE194_Unexpected_Sign_Extension__rand_malloc_01_good();


	printLine("Calling CWE194_Unexpected_Sign_Extension__rand_malloc_52_good();");
	CWE194_Unexpected_Sign_Extension__rand_malloc_52_good();


	printLine("Calling CWE194_Unexpected_Sign_Extension__rand_memcpy_01_good();");
	CWE194_Unexpected_Sign_Extension__rand_memcpy_01_good();


	printLine("Calling CWE194_Unexpected_Sign_Extension__rand_memcpy_52_good();");
	CWE194_Unexpected_Sign_Extension__rand_memcpy_52_good();


	printLine("Calling CWE194_Unexpected_Sign_Extension__rand_memmove_01_good();");
	CWE194_Unexpected_Sign_Extension__rand_memmove_01_good();


	printLine("Calling CWE194_Unexpected_Sign_Extension__rand_memmove_52_good();");
	CWE194_Unexpected_Sign_Extension__rand_memmove_52_good();


	printLine("Calling CWE194_Unexpected_Sign_Extension__rand_strncpy_01_good();");
	CWE194_Unexpected_Sign_Extension__rand_strncpy_01_good();


	printLine("Calling CWE194_Unexpected_Sign_Extension__rand_strncpy_52_good();");
	CWE194_Unexpected_Sign_Extension__rand_strncpy_52_good();


	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */


#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */

	printLine("Calling CWE194_Unexpected_Sign_Extension__listen_socket_malloc_01_bad();");
	CWE194_Unexpected_Sign_Extension__listen_socket_malloc_01_bad();


	printLine("Calling CWE194_Unexpected_Sign_Extension__listen_socket_malloc_52_bad();");
	CWE194_Unexpected_Sign_Extension__listen_socket_malloc_52_bad();

	printLine("Calling CWE194_Unexpected_Sign_Extension__listen_socket_memcpy_01_bad();");
	CWE194_Unexpected_Sign_Extension__listen_socket_memcpy_01_bad();


	printLine("Calling CWE194_Unexpected_Sign_Extension__listen_socket_memcpy_52_bad();");
	CWE194_Unexpected_Sign_Extension__listen_socket_memcpy_52_bad();

	printLine("Calling CWE194_Unexpected_Sign_Extension__listen_socket_memmove_01_bad();");
	CWE194_Unexpected_Sign_Extension__listen_socket_memmove_01_bad();


	printLine("Calling CWE194_Unexpected_Sign_Extension__listen_socket_memmove_52_bad();");
	CWE194_Unexpected_Sign_Extension__listen_socket_memmove_52_bad();


	printLine("Calling CWE194_Unexpected_Sign_Extension__listen_socket_strncpy_01_bad();");
	CWE194_Unexpected_Sign_Extension__listen_socket_strncpy_01_bad();

	printLine("Calling CWE194_Unexpected_Sign_Extension__listen_socket_strncpy_52_bad();");
	CWE194_Unexpected_Sign_Extension__listen_socket_strncpy_52_bad();

	printLine("Calling CWE194_Unexpected_Sign_Extension__negative_malloc_01_bad();");
	CWE194_Unexpected_Sign_Extension__negative_malloc_01_bad();


	printLine("Calling CWE194_Unexpected_Sign_Extension__negative_malloc_52_bad();");
	CWE194_Unexpected_Sign_Extension__negative_malloc_52_bad();

	printLine("Calling CWE194_Unexpected_Sign_Extension__negative_memcpy_01_bad();");
	CWE194_Unexpected_Sign_Extension__negative_memcpy_01_bad();


	printLine("Calling CWE194_Unexpected_Sign_Extension__negative_memcpy_52_bad();");
	CWE194_Unexpected_Sign_Extension__negative_memcpy_52_bad();


	printLine("Calling CWE194_Unexpected_Sign_Extension__negative_memmove_01_bad();");
	CWE194_Unexpected_Sign_Extension__negative_memmove_01_bad();


	printLine("Calling CWE194_Unexpected_Sign_Extension__negative_memmove_52_bad();");
	CWE194_Unexpected_Sign_Extension__negative_memmove_52_bad();

	printLine("Calling CWE194_Unexpected_Sign_Extension__negative_strncpy_01_bad();");
	CWE194_Unexpected_Sign_Extension__negative_strncpy_01_bad();


	printLine("Calling CWE194_Unexpected_Sign_Extension__negative_strncpy_52_bad();");
	CWE194_Unexpected_Sign_Extension__negative_strncpy_52_bad();


	printLine("Calling CWE194_Unexpected_Sign_Extension__rand_malloc_01_bad();");
	CWE194_Unexpected_Sign_Extension__rand_malloc_01_bad();


	printLine("Calling CWE194_Unexpected_Sign_Extension__rand_malloc_52_bad();");
	CWE194_Unexpected_Sign_Extension__rand_malloc_52_bad();


	printLine("Calling CWE194_Unexpected_Sign_Extension__rand_memcpy_01_bad();");
	CWE194_Unexpected_Sign_Extension__rand_memcpy_01_bad();


	printLine("Calling CWE194_Unexpected_Sign_Extension__rand_memcpy_52_bad();");
	CWE194_Unexpected_Sign_Extension__rand_memcpy_52_bad();


	printLine("Calling CWE194_Unexpected_Sign_Extension__rand_memmove_01_bad();");
	CWE194_Unexpected_Sign_Extension__rand_memmove_01_bad();


	printLine("Calling CWE194_Unexpected_Sign_Extension__rand_memmove_52_bad();");
	CWE194_Unexpected_Sign_Extension__rand_memmove_52_bad();


	printLine("Calling CWE194_Unexpected_Sign_Extension__rand_strncpy_01_bad();");
	CWE194_Unexpected_Sign_Extension__rand_strncpy_01_bad();


	printLine("Calling CWE194_Unexpected_Sign_Extension__rand_strncpy_52_bad();");
	CWE194_Unexpected_Sign_Extension__rand_strncpy_52_bad();

#endif /* OMITBAD */

	return 0;

} 
