/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__src_char_declare_cpy_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__src_char_declare_cpy_01_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__src_char_declare_cpy_52_good();");
	CWE121_Stack_Based_Buffer_Overflow__src_char_declare_cpy_52_good();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_alloca_cat_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_alloca_cat_01_good();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_alloca_cat_52_good();");
	CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_alloca_cat_52_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_alloca_cpy_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_alloca_cpy_01_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_alloca_cpy_52_good();");
	CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_alloca_cpy_52_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_declare_cat_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_declare_cat_01_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_declare_cat_52_good();");
	CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_declare_cat_52_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_declare_cpy_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_declare_cpy_01_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_declare_cpy_52_good();");
	CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_declare_cpy_52_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__wchar_t_type_overrun_memcpy_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__wchar_t_type_overrun_memcpy_01_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__wchar_t_type_overrun_memmove_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__wchar_t_type_overrun_memmove_01_good();


	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */


#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	
	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__src_char_declare_cpy_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__src_char_declare_cpy_01_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__src_char_declare_cpy_52_bad();");
	CWE121_Stack_Based_Buffer_Overflow__src_char_declare_cpy_52_bad();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_alloca_cat_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_alloca_cat_01_bad();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_alloca_cat_52_bad();");
	CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_alloca_cat_52_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_alloca_cpy_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_alloca_cpy_01_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_alloca_cpy_52_bad();");
	CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_alloca_cpy_52_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_declare_cat_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_declare_cat_01_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_declare_cat_52_bad();");
	CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_declare_cat_52_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_declare_cpy_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_declare_cpy_01_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_declare_cpy_52_bad();");
	CWE121_Stack_Based_Buffer_Overflow__src_wchar_t_declare_cpy_52_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__wchar_t_type_overrun_memcpy_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__wchar_t_type_overrun_memcpy_01_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__wchar_t_type_overrun_memmove_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__wchar_t_type_overrun_memmove_01_bad();
#endif /* OMITBAD */

	return 0;

} 
