/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_loop_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_loop_01_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_loop_54_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_loop_54_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_memcpy_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_memcpy_01_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_memcpy_54_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_memcpy_54_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_memmove_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_memmove_01_good();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_memmove_54_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_memmove_54_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_ncpy_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_ncpy_01_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_ncpy_54_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_ncpy_54_good();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_cpy_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_cpy_01_good();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_cpy_54_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_cpy_54_good();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_loop_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_loop_01_good();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_loop_54_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_loop_54_good();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_memcpy_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_memcpy_01_good();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_memcpy_54_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_memcpy_54_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_memmove_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_memmove_01_good();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_memmove_54_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_memmove_54_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_ncpy_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_ncpy_01_good();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_ncpy_54_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_ncpy_54_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_cpy_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_cpy_01_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_cpy_54_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_cpy_54_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_loop_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_loop_01_good();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_loop_54_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_loop_54_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_memcpy_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_memcpy_01_good();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_memcpy_54_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_memcpy_54_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_memmove_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_memmove_01_good();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_memmove_54_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_memmove_54_good();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_ncpy_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_ncpy_01_good();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_ncpy_54_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_ncpy_54_good();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_declare_cpy_01_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_declare_cpy_01_good();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_declare_cpy_54_good();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_declare_cpy_54_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */






#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
		printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_loop_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_loop_01_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_loop_54_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_loop_54_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_memcpy_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_memcpy_01_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_memcpy_54_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_memcpy_54_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_memmove_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_memmove_01_bad();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_memmove_54_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_memmove_54_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_ncpy_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_ncpy_01_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_ncpy_54_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_alloca_ncpy_54_bad();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_cpy_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_cpy_01_bad();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_cpy_54_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_cpy_54_bad();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_loop_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_loop_01_bad();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_loop_54_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_loop_54_bad();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_memcpy_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_memcpy_01_bad();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_memcpy_54_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_memcpy_54_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_memmove_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_memmove_01_bad();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_memmove_54_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_memmove_54_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_ncpy_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_ncpy_01_bad();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_ncpy_54_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_char_declare_ncpy_54_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_cpy_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_cpy_01_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_cpy_54_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_cpy_54_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_loop_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_loop_01_bad();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_loop_54_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_loop_54_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_memcpy_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_memcpy_01_bad();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_memcpy_54_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_memcpy_54_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_memmove_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_memmove_01_bad();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_memmove_54_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_memmove_54_bad();

	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_ncpy_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_ncpy_01_bad();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_ncpy_54_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_alloca_ncpy_54_bad();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_declare_cpy_01_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_declare_cpy_01_bad();


	printLine("Calling CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_declare_cpy_54_bad();");
	CWE121_Stack_Based_Buffer_Overflow__CWE193_wchar_t_declare_cpy_54_bad();

#endif /* OMITBAD */

	return 0;

} 
