/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE758_Undefined_Behavior__char_alloca_use_01_good();");
	CWE758_Undefined_Behavior__char_alloca_use_01_good();


	printLine("Calling CWE758_Undefined_Behavior__char_malloc_use_01_good();");
	CWE758_Undefined_Behavior__char_malloc_use_01_good();


	printLine("Calling CWE758_Undefined_Behavior__char_pointer_alloca_use_01_good();");
	CWE758_Undefined_Behavior__char_pointer_alloca_use_01_good();


	printLine("Calling CWE758_Undefined_Behavior__char_pointer_malloc_use_01_good();");
	CWE758_Undefined_Behavior__char_pointer_malloc_use_01_good();


	printLine("Calling CWE758_Undefined_Behavior__double_pointer_alloca_use_01_good();");
	CWE758_Undefined_Behavior__double_pointer_alloca_use_01_good();


	printLine("Calling CWE758_Undefined_Behavior__double_pointer_malloc_use_01_good();");
	CWE758_Undefined_Behavior__double_pointer_malloc_use_01_good();


	printLine("Calling CWE758_Undefined_Behavior__int64_t_alloca_use_01_good();");
	CWE758_Undefined_Behavior__int64_t_alloca_use_01_good();


	printLine("Calling CWE758_Undefined_Behavior__int64_t_malloc_use_01_good();");
	CWE758_Undefined_Behavior__int64_t_malloc_use_01_good();


	printLine("Calling CWE758_Undefined_Behavior__int_alloca_use_01_good();");
	CWE758_Undefined_Behavior__int_alloca_use_01_good();


	printLine("Calling CWE758_Undefined_Behavior__int_malloc_use_01_good();");
	CWE758_Undefined_Behavior__int_malloc_use_01_good();


	printLine("Calling CWE758_Undefined_Behavior__int_pointer_alloca_use_01_good();");
	CWE758_Undefined_Behavior__int_pointer_alloca_use_01_good();


	printLine("Calling CWE758_Undefined_Behavior__int_pointer_malloc_use_01_good();");
	CWE758_Undefined_Behavior__int_pointer_malloc_use_01_good();


	printLine("Calling CWE758_Undefined_Behavior__long_alloca_use_01_good();");
	CWE758_Undefined_Behavior__long_alloca_use_01_good();


	printLine("Calling CWE758_Undefined_Behavior__long_malloc_use_01_good();");
	CWE758_Undefined_Behavior__long_malloc_use_01_good();


	printLine("Calling CWE758_Undefined_Behavior__no_return_01_good();");
	CWE758_Undefined_Behavior__no_return_01_good();

	printLine("Calling CWE758_Undefined_Behavior__struct_alloca_use_01_good();");
	CWE758_Undefined_Behavior__struct_alloca_use_01_good();


	printLine("Calling CWE758_Undefined_Behavior__struct_malloc_use_01_good();");
	CWE758_Undefined_Behavior__struct_malloc_use_01_good();


	printLine("Calling CWE758_Undefined_Behavior__struct_pointer_alloca_use_01_good();");
	CWE758_Undefined_Behavior__struct_pointer_alloca_use_01_good();


	printLine("Calling CWE758_Undefined_Behavior__struct_pointer_malloc_use_01_good();");
	CWE758_Undefined_Behavior__struct_pointer_malloc_use_01_good();


	printLine("Calling CWE758_Undefined_Behavior__w32_bare_return_01_good();");
	CWE758_Undefined_Behavior__w32_bare_return_01_good();

	printLine("Calling CWE758_Undefined_Behavior__w32_bare_return_implicit_01_good();");
	CWE758_Undefined_Behavior__w32_bare_return_implicit_01_good();

	printLine("Calling CWE758_Undefined_Behavior__w32_no_return_implicit_01_good();");
	CWE758_Undefined_Behavior__w32_no_return_implicit_01_good();

	printLine("Calling CWE758_Undefined_Behavior__w32_return_implicit_01_good();");
	CWE758_Undefined_Behavior__w32_return_implicit_01_good();

	printLine("Calling CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_01_good();");
	CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_01_good();


	printLine("Calling CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_01_good();");
	CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_01_good();


	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */


#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	
	printLine("Calling CWE758_Undefined_Behavior__char_alloca_use_01_bad();");
	CWE758_Undefined_Behavior__char_alloca_use_01_bad();


	printLine("Calling CWE758_Undefined_Behavior__char_malloc_use_01_bad();");
	CWE758_Undefined_Behavior__char_malloc_use_01_bad();


	printLine("Calling CWE758_Undefined_Behavior__char_pointer_alloca_use_01_bad();");
	CWE758_Undefined_Behavior__char_pointer_alloca_use_01_bad();


	printLine("Calling CWE758_Undefined_Behavior__char_pointer_malloc_use_01_bad();");
	CWE758_Undefined_Behavior__char_pointer_malloc_use_01_bad();


	printLine("Calling CWE758_Undefined_Behavior__double_pointer_alloca_use_01_bad();");
	CWE758_Undefined_Behavior__double_pointer_alloca_use_01_bad();


	printLine("Calling CWE758_Undefined_Behavior__double_pointer_malloc_use_01_bad();");
	CWE758_Undefined_Behavior__double_pointer_malloc_use_01_bad();


	printLine("Calling CWE758_Undefined_Behavior__int64_t_alloca_use_01_bad();");
	CWE758_Undefined_Behavior__int64_t_alloca_use_01_bad();


	printLine("Calling CWE758_Undefined_Behavior__int64_t_malloc_use_01_bad();");
	CWE758_Undefined_Behavior__int64_t_malloc_use_01_bad();


	printLine("Calling CWE758_Undefined_Behavior__int_alloca_use_01_bad();");
	CWE758_Undefined_Behavior__int_alloca_use_01_bad();


	printLine("Calling CWE758_Undefined_Behavior__int_malloc_use_01_bad();");
	CWE758_Undefined_Behavior__int_malloc_use_01_bad();


	printLine("Calling CWE758_Undefined_Behavior__int_pointer_alloca_use_01_bad();");
	CWE758_Undefined_Behavior__int_pointer_alloca_use_01_bad();


	printLine("Calling CWE758_Undefined_Behavior__int_pointer_malloc_use_01_bad();");
	CWE758_Undefined_Behavior__int_pointer_malloc_use_01_bad();


	printLine("Calling CWE758_Undefined_Behavior__long_alloca_use_01_bad();");
	CWE758_Undefined_Behavior__long_alloca_use_01_bad();


	printLine("Calling CWE758_Undefined_Behavior__long_malloc_use_01_bad();");
	CWE758_Undefined_Behavior__long_malloc_use_01_bad();


	printLine("Calling CWE758_Undefined_Behavior__no_return_01_bad();");
	CWE758_Undefined_Behavior__no_return_01_bad();

	printLine("Calling CWE758_Undefined_Behavior__struct_alloca_use_01_bad();");
	CWE758_Undefined_Behavior__struct_alloca_use_01_bad();


	printLine("Calling CWE758_Undefined_Behavior__struct_malloc_use_01_bad();");
	CWE758_Undefined_Behavior__struct_malloc_use_01_bad();


	printLine("Calling CWE758_Undefined_Behavior__struct_pointer_alloca_use_01_bad();");
	CWE758_Undefined_Behavior__struct_pointer_alloca_use_01_bad();


	printLine("Calling CWE758_Undefined_Behavior__struct_pointer_malloc_use_01_bad();");
	CWE758_Undefined_Behavior__struct_pointer_malloc_use_01_bad();


	printLine("Calling CWE758_Undefined_Behavior__w32_bare_return_01_bad();");
	CWE758_Undefined_Behavior__w32_bare_return_01_bad();

	printLine("Calling CWE758_Undefined_Behavior__w32_bare_return_implicit_01_bad();");
	CWE758_Undefined_Behavior__w32_bare_return_implicit_01_bad();

	printLine("Calling CWE758_Undefined_Behavior__w32_no_return_implicit_01_bad();");
	CWE758_Undefined_Behavior__w32_no_return_implicit_01_bad();

	printLine("Calling CWE758_Undefined_Behavior__w32_return_implicit_01_bad();");
	CWE758_Undefined_Behavior__w32_return_implicit_01_bad();

	printLine("Calling CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_01_bad();");
	CWE758_Undefined_Behavior__wchar_t_pointer_alloca_use_01_bad();


	printLine("Calling CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_01_bad();");
	CWE758_Undefined_Behavior__wchar_t_pointer_malloc_use_01_bad();
#endif /* OMITBAD */

	return 0;

} 
