/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_connect_socket_01_good();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_connect_socket_01_good();


	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_connect_socket_16_good();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_connect_socket_16_good();


	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fgets_01_good();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fgets_01_good();


	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fgets_16_good();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fgets_16_good();


	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fixed_01_good();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fixed_01_good();


	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fixed_16_good();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fixed_16_good();


	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fscanf_01_good();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fscanf_01_good();


	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fscanf_16_good();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fscanf_16_good();


	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_listen_socket_01_good();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_listen_socket_01_good();


	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_listen_socket_16_good();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_listen_socket_16_good();


	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_rand_01_good();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_rand_01_good();

	
	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_rand_16_good();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_rand_16_good();


#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	
	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_connect_socket_01_bad();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_connect_socket_01_bad();


	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_connect_socket_16_bad();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_connect_socket_16_bad();


	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fgets_01_bad();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fgets_01_bad();


	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fgets_16_bad();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fgets_16_bad();


	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fixed_01_bad();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fixed_01_bad();


	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fixed_16_bad();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fixed_16_bad();


	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fscanf_01_bad();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fscanf_01_bad();


	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fscanf_16_bad();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_fscanf_16_bad();


	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_listen_socket_01_bad();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_listen_socket_01_bad();


	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_listen_socket_16_bad();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_listen_socket_16_bad();


	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_rand_01_bad();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_rand_01_bad();

	
	printLine("Calling CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_rand_16_bad();");
	CWE680_Integer_Overflow_to_Buffer_Overflow__malloc_rand_16_bad();
#endif /* OMITBAD */

	return 0;

} 
