/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__fopen_01_good();");
	CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__fopen_01_good();


	printLine("Calling CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__fopen_05_good();");
	CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__fopen_05_good();


	printLine("Calling CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__open_01_good();");
	CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__open_01_good();

	printLine("Calling CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__open_05_good();");
	CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__open_05_good();


	printLine("Calling CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__w32CreateFile_01_good();");
	CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__w32CreateFile_01_good();

	printLine("Calling CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__w32CreateFile_05_good();");
	CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__w32CreateFile_05_good();


	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */



#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	printLine("Calling CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__fopen_01_bad();");
	CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__fopen_01_bad();

	printLine("Calling CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__fopen_05_bad();");
	CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__fopen_05_bad();


	printLine("Calling CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__open_01_bad();");
	CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__open_01_bad();


	printLine("Calling CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__open_05_bad();");
	CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__open_05_bad();


	printLine("Calling CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__w32CreateFile_01_bad();");
	CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__w32CreateFile_01_bad();


	printLine("Calling CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__w32CreateFile_05_bad();");
	CWE773_Missing_Reference_to_Active_File_Descriptor_or_Handle__w32CreateFile_05_bad();


#endif /* OMITBAD */

	return 0;

} 
