/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_long_static_01_good();");
	CWE590_Free_Memory_Not_on_Heap__free_long_static_01_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_long_static_07_good();");
	CWE590_Free_Memory_Not_on_Heap__free_long_static_07_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_01_good();");
	CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_01_good();

	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_07_good();");
	CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_07_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_struct_declare_01_good();");
	CWE590_Free_Memory_Not_on_Heap__free_struct_declare_01_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_struct_declare_07_good();");
	CWE590_Free_Memory_Not_on_Heap__free_struct_declare_07_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_struct_static_01_good();");
	CWE590_Free_Memory_Not_on_Heap__free_struct_static_01_good();

	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_struct_static_07_good();");
	CWE590_Free_Memory_Not_on_Heap__free_struct_static_07_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_01_good();");
	CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_01_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_07_good();");
	CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_07_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_01_good();");
	CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_01_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_07_good();");
	CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_07_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_01_good();");
	CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_01_good();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_07_good();");
	CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_07_good();


#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	
	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_long_static_01_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_long_static_01_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_long_static_07_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_long_static_07_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_01_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_01_bad();

	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_07_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_struct_alloca_07_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_struct_declare_01_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_struct_declare_01_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_struct_declare_07_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_struct_declare_07_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_struct_static_01_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_struct_static_01_bad();

	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_struct_static_07_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_struct_static_07_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_01_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_01_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_07_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_wchar_t_alloca_07_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_01_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_01_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_07_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_wchar_t_declare_07_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_01_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_01_bad();


	printLine("Calling CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_07_bad();");
	CWE590_Free_Memory_Not_on_Heap__free_wchar_t_static_07_bad();
#endif /* OMITBAD */

	return 0;

} 
