/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE401_Memory_Leak__strdup_wchar_t_01_good();");
	CWE401_Memory_Leak__strdup_wchar_t_01_good();

	printLine("Calling CWE401_Memory_Leak__struct_twoIntsStruct_calloc_01_good();");
	CWE401_Memory_Leak__struct_twoIntsStruct_calloc_01_good();


	printLine("Calling CWE401_Memory_Leak__struct_twoIntsStruct_malloc_01_good();");
	CWE401_Memory_Leak__struct_twoIntsStruct_malloc_01_good();


	printLine("Calling CWE401_Memory_Leak__struct_twoIntsStruct_realloc_01_good();");
	CWE401_Memory_Leak__struct_twoIntsStruct_realloc_01_good();


	printLine("Calling CWE401_Memory_Leak__twoIntsStruct_calloc_01_good();");
	CWE401_Memory_Leak__twoIntsStruct_calloc_01_good();


	printLine("Calling CWE401_Memory_Leak__twoIntsStruct_malloc_01_good();");
	CWE401_Memory_Leak__twoIntsStruct_malloc_01_good();


	printLine("Calling CWE401_Memory_Leak__twoIntsStruct_realloc_01_good();");
	CWE401_Memory_Leak__twoIntsStruct_realloc_01_good();


	printLine("Calling CWE401_Memory_Leak__wchar_t_calloc_01_good();");
	CWE401_Memory_Leak__wchar_t_calloc_01_good();

	printLine("Calling CWE401_Memory_Leak__wchar_t_malloc_01_good();");
	CWE401_Memory_Leak__wchar_t_malloc_01_good();


	printLine("Calling CWE401_Memory_Leak__wchar_t_realloc_01_good();");
	CWE401_Memory_Leak__wchar_t_realloc_01_good();


	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */


#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	printLine("Calling CWE401_Memory_Leak__strdup_wchar_t_01_bad();");
	CWE401_Memory_Leak__strdup_wchar_t_01_bad();

	printLine("Calling CWE401_Memory_Leak__struct_twoIntsStruct_calloc_01_bad();");
	CWE401_Memory_Leak__struct_twoIntsStruct_calloc_01_bad();


	printLine("Calling CWE401_Memory_Leak__struct_twoIntsStruct_malloc_01_bad();");
	CWE401_Memory_Leak__struct_twoIntsStruct_malloc_01_bad();


	printLine("Calling CWE401_Memory_Leak__struct_twoIntsStruct_realloc_01_bad();");
	CWE401_Memory_Leak__struct_twoIntsStruct_realloc_01_bad();


	printLine("Calling CWE401_Memory_Leak__twoIntsStruct_calloc_01_bad();");
	CWE401_Memory_Leak__twoIntsStruct_calloc_01_bad();


	printLine("Calling CWE401_Memory_Leak__twoIntsStruct_malloc_01_bad();");
	CWE401_Memory_Leak__twoIntsStruct_malloc_01_bad();


	printLine("Calling CWE401_Memory_Leak__twoIntsStruct_realloc_01_bad();");
	CWE401_Memory_Leak__twoIntsStruct_realloc_01_bad();


	printLine("Calling CWE401_Memory_Leak__wchar_t_calloc_01_bad();");
	CWE401_Memory_Leak__wchar_t_calloc_01_bad();

	printLine("Calling CWE401_Memory_Leak__wchar_t_malloc_01_bad();");
	CWE401_Memory_Leak__wchar_t_malloc_01_bad();


	printLine("Calling CWE401_Memory_Leak__wchar_t_realloc_01_bad();");
	CWE401_Memory_Leak__wchar_t_realloc_01_bad();
#endif /* OMITBAD */

	return 0;

} 
