/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE369_Divide_by_Zero__float_connect_socket_01_good();");
	CWE369_Divide_by_Zero__float_connect_socket_01_good();


	printLine("Calling CWE369_Divide_by_Zero__float_connect_socket_22_good();");
	CWE369_Divide_by_Zero__float_connect_socket_22_good();


	printLine("Calling CWE369_Divide_by_Zero__float_fgets_01_good();");
	CWE369_Divide_by_Zero__float_fgets_01_good();

	printLine("Calling CWE369_Divide_by_Zero__float_fgets_02_good();");
	CWE369_Divide_by_Zero__float_fgets_02_good();


	printLine("Calling CWE369_Divide_by_Zero__float_fscanf_01_good();");
	CWE369_Divide_by_Zero__float_fscanf_01_good();

	printLine("Calling CWE369_Divide_by_Zero__float_fscanf_03_good();");
	CWE369_Divide_by_Zero__float_fscanf_03_good();


	printLine("Calling CWE369_Divide_by_Zero__float_listenSocket_01_good();");
	CWE369_Divide_by_Zero__float_listenSocket_01_good();


	printLine("Calling CWE369_Divide_by_Zero__float_listenSocket_04_good();");
	CWE369_Divide_by_Zero__float_listenSocket_04_good();


	printLine("Calling CWE369_Divide_by_Zero__float_rand_01_good();");
	CWE369_Divide_by_Zero__float_rand_01_good();

	printLine("Calling CWE369_Divide_by_Zero__float_rand_05_good();");
	CWE369_Divide_by_Zero__float_rand_05_good();


	printLine("Calling CWE369_Divide_by_Zero__float_zero_01_good();");
	CWE369_Divide_by_Zero__float_zero_01_good();

	printLine("Calling CWE369_Divide_by_Zero__float_zero_06_good();");
	CWE369_Divide_by_Zero__float_zero_06_good();


	printLine("Calling CWE369_Divide_by_Zero__int_connect_socket_divide_01_good();");
	CWE369_Divide_by_Zero__int_connect_socket_divide_01_good();


	printLine("Calling CWE369_Divide_by_Zero__int_connect_socket_divide_07_good();");
	CWE369_Divide_by_Zero__int_connect_socket_divide_07_good();


	printLine("Calling CWE369_Divide_by_Zero__int_connect_socket_modulo_01_good();");
	CWE369_Divide_by_Zero__int_connect_socket_modulo_01_good();


	printLine("Calling CWE369_Divide_by_Zero__int_connect_socket_modulo_08_good();");
	CWE369_Divide_by_Zero__int_connect_socket_modulo_08_good();


	printLine("Calling CWE369_Divide_by_Zero__int_fgets_divide_01_good();");
	CWE369_Divide_by_Zero__int_fgets_divide_01_good();


	printLine("Calling CWE369_Divide_by_Zero__int_fgets_divide_09_good();");
	CWE369_Divide_by_Zero__int_fgets_divide_09_good();


	printLine("Calling CWE369_Divide_by_Zero__int_fgets_modulo_01_good();");
	CWE369_Divide_by_Zero__int_fgets_modulo_01_good();


	printLine("Calling CWE369_Divide_by_Zero__int_fgets_modulo_10_good();");
	CWE369_Divide_by_Zero__int_fgets_modulo_10_good();


	printLine("Calling CWE369_Divide_by_Zero__int_fscanf_divide_01_good();");
	CWE369_Divide_by_Zero__int_fscanf_divide_01_good();

	printLine("Calling CWE369_Divide_by_Zero__int_fscanf_divide_11_good();");
	CWE369_Divide_by_Zero__int_fscanf_divide_11_good();


	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */


#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	
	printLine("Calling CWE369_Divide_by_Zero__float_connect_socket_01_bad();");
	CWE369_Divide_by_Zero__float_connect_socket_01_bad();


	printLine("Calling CWE369_Divide_by_Zero__float_connect_socket_22_bad();");
	CWE369_Divide_by_Zero__float_connect_socket_22_bad();


	printLine("Calling CWE369_Divide_by_Zero__float_fgets_01_bad();");
	CWE369_Divide_by_Zero__float_fgets_01_bad();

	printLine("Calling CWE369_Divide_by_Zero__float_fgets_02_bad();");
	CWE369_Divide_by_Zero__float_fgets_02_bad();


	printLine("Calling CWE369_Divide_by_Zero__float_fscanf_01_bad();");
	CWE369_Divide_by_Zero__float_fscanf_01_bad();

	printLine("Calling CWE369_Divide_by_Zero__float_fscanf_03_bad();");
	CWE369_Divide_by_Zero__float_fscanf_03_bad();


	printLine("Calling CWE369_Divide_by_Zero__float_listenSocket_01_bad();");
	CWE369_Divide_by_Zero__float_listenSocket_01_bad();


	printLine("Calling CWE369_Divide_by_Zero__float_listenSocket_04_bad();");
	CWE369_Divide_by_Zero__float_listenSocket_04_bad();


	printLine("Calling CWE369_Divide_by_Zero__float_rand_01_bad();");
	CWE369_Divide_by_Zero__float_rand_01_bad();

	printLine("Calling CWE369_Divide_by_Zero__float_rand_05_bad();");
	CWE369_Divide_by_Zero__float_rand_05_bad();


	printLine("Calling CWE369_Divide_by_Zero__float_zero_01_bad();");
	CWE369_Divide_by_Zero__float_zero_01_bad();

	printLine("Calling CWE369_Divide_by_Zero__float_zero_06_bad();");
	CWE369_Divide_by_Zero__float_zero_06_bad();


	printLine("Calling CWE369_Divide_by_Zero__int_connect_socket_divide_01_bad();");
	CWE369_Divide_by_Zero__int_connect_socket_divide_01_bad();


	printLine("Calling CWE369_Divide_by_Zero__int_connect_socket_divide_07_bad();");
	CWE369_Divide_by_Zero__int_connect_socket_divide_07_bad();


	printLine("Calling CWE369_Divide_by_Zero__int_connect_socket_modulo_01_bad();");
	CWE369_Divide_by_Zero__int_connect_socket_modulo_01_bad();


	printLine("Calling CWE369_Divide_by_Zero__int_connect_socket_modulo_08_bad();");
	CWE369_Divide_by_Zero__int_connect_socket_modulo_08_bad();


	printLine("Calling CWE369_Divide_by_Zero__int_fgets_divide_01_bad();");
	CWE369_Divide_by_Zero__int_fgets_divide_01_bad();


	printLine("Calling CWE369_Divide_by_Zero__int_fgets_divide_09_bad();");
	CWE369_Divide_by_Zero__int_fgets_divide_09_bad();


	printLine("Calling CWE369_Divide_by_Zero__int_fgets_modulo_01_bad();");
	CWE369_Divide_by_Zero__int_fgets_modulo_01_bad();


	printLine("Calling CWE369_Divide_by_Zero__int_fgets_modulo_10_bad();");
	CWE369_Divide_by_Zero__int_fgets_modulo_10_bad();


	printLine("Calling CWE369_Divide_by_Zero__int_fscanf_divide_01_bad();");
	CWE369_Divide_by_Zero__int_fscanf_divide_01_bad();

	printLine("Calling CWE369_Divide_by_Zero__int_fscanf_divide_11_bad();");
	CWE369_Divide_by_Zero__int_fscanf_divide_11_bad();
#endif /* OMITBAD */

	return 0;

} 
